const c=document.getElementById('game'),x=c.getContext('2d'),q=s=>document.getElementById(s);
const VW=960,VH=540,WW=1900,WH=1180;
const U={hp:q('hp-fill'),hpt:q('hp-text'),room:q('room-text'),gold:q('gold-text'),crit:q('crit-text'),cd:q('crit-damage-text'),d1:q('die-one'),d2:q('die-two'),res:q('roll-result'),roll:q('roll-btn'),dodge:q('dodge-btn'),start:q('start-screen'),up:q('upgrade-screen'),ups:q('upgrade-options'),shop:q('shop-screen'),shopGold:q('shop-gold'),shopOptions:q('shop-options'),leaveShop:q('leave-shop-btn'),toast:q('pickup-toast'),over:q('game-over-screen'),stats:q('game-over-stats'),db:q('damage-bonus-text'),spd:q('speed-text'),rng:q('range-text'),dash:q('dash-text'),explored:q('explored-text'),turn:q('turn-label')};
let state='menu',mode='explore',floorNum=1,gold=0,kills=0,enemies=[],texts=[],particles=[],selected=null,turn='none',busy=false,shake=0,keys={},encounterIds=new Set(),remainingEncounters=0,cover=[],loot=[],discovered=new Set(),cam={x:0,y:0};
const p={x:120,y:WH/2,r:15,hp:100,max:100,bonus:0,crit:.10,critDmg:2,range:130,step:55,exploreSpeed:190,armor:0,fx:1,fy:0,dodge:2,maxDodge:2,dodgeRecharge:0,dodging:false};
const upgrades=[['Loaded Dice','+2 damage to every roll.',()=>p.bonus+=2],['Sharp Edges','+8% critical-hit chance.',()=>p.crit=Math.min(.75,p.crit+.08)],['Deadly Fortune','+0.5× critical damage.',()=>p.critDmg+=.5],['Iron Heart','+20 max HP and heal 20.',()=>{p.max+=20;p.hp=Math.min(p.max,p.hp+20)}],['Long Stride','Move 10 farther each combat turn.',()=>p.step+=10],['Long Reach','+25 attack range.',()=>p.range+=25],['Second Wind','Heal 45 HP.',()=>p.hp=Math.min(p.max,p.hp+45)],['Bone Armor','Reduce incoming damage by 2.',()=>p.armor+=2],['Lucky Pockets','Gold pickups are worth 50% more.',()=>p.goldMult=(p.goldMult||1)*1.5]];
const shopStock=[
 ['Full Heal',35,'Restore all HP.',()=>p.hp=p.max],
 ['Heart Container',70,'Gain 20 max HP and heal 20.',()=>{p.max+=20;p.hp=Math.min(p.max,p.hp+20)}],
 ['Weighted Die',65,'Permanently gain +2 roll damage.',()=>p.bonus+=2],
 ['Precision Charm',75,'Permanently gain +7% crit chance.',()=>p.crit=Math.min(.8,p.crit+.07)],
 ['Bone Plating',80,'Permanently reduce damage by 1.',()=>p.armor+=1],
 ['Traveler Boots',60,'Move faster while exploring.',()=>p.exploreSpeed+=22],
 ['Dodge Flask',90,'Gain one maximum dodge charge.',()=>{p.maxDodge++;p.dodge=p.maxDodge}],
 ['Longbow String',55,'Increase attack range by 20.',()=>p.range+=20]
];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function id(){return crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}
function toast(msg){U.toast.textContent=msg;U.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>U.toast.classList.remove('show'),1300)}
function reset(){floorNum=1;gold=0;kills=0;enemies=[];texts=[];particles=[];selected=null;turn='none';busy=false;mode='explore';encounterIds.clear();discovered.clear();Object.assign(p,{x:120,y:WH/2,hp:100,max:100,bonus:0,crit:.10,critDmg:2,range:130,step:55,exploreSpeed:190,armor:0,fx:1,fy:0,dodge:2,maxDodge:2,dodgeRecharge:0,dodging:false,goldMult:1});spawnFloor();ui()}
function rectOverlap(a,b,pad=25){return a.x<a.x+a.w&&a.x-pad<b.x+b.w&&a.x+a.w+pad>b.x&&a.y-pad<b.y+b.h&&a.y+a.h+pad>b.y}
function validSpot(px,py,r=30){return px>70&&px<WW-70&&py>70&&py<WH-70&&!cover.some(o=>px+r>o.x&&px-r<o.x+o.w&&py+r>o.y&&py-r<o.y+o.h)}
function spawnCover(){cover=[];const fixed=[{x:420,y:170,w:70,h:150,type:'pillar'},{x:760,y:650,w:180,h:45,type:'wall'},{x:1120,y:260,w:60,h:150,type:'statue'},{x:1450,y:790,w:85,h:85,type:'crate'}];cover.push(...fixed);for(let i=0;i<15;i++){let w=45+Math.random()*100,h=40+Math.random()*90,tries=0,o;do{o={x:220+Math.random()*(WW-380),y:70+Math.random()*(WH-140),w,h,type:['pillar','wall','statue','crate'][Math.floor(Math.random()*4)]};tries++}while((cover.some(z=>!(o.x+o.w+45<z.x||o.x>z.x+z.w+45||o.y+o.h+45<z.y||o.y>z.y+z.h+45))||Math.hypot(o.x-p.x,o.y-p.y)<180)&&tries<60);if(tries<60)cover.push(o)}}
function spawnLoot(){loot=[];const count=12+Math.floor(floorNum*.8);for(let i=0;i<count;i++){let px,py,tries=0;do{px=120+Math.random()*(WW-240);py=80+Math.random()*(WH-160);tries++}while(!validSpot(px,py,25)&&tries<80);const r=Math.random(),type=r<.47?'gold':r<.78?'health':'chest';loot.push({id:id(),type,x:px,y:py,r:type==='chest'?18:12,opened:false})}}
function spawnFloor(){enemies=[];loot=[];selected=null;encounterIds.clear();mode='explore';turn='none';p.x=120;p.y=WH/2;p.dodge=p.maxDodge;p.dodgeRecharge=0;p.dodging=false;spawnCover();spawnLoot();const groups=Math.min(8,3+Math.floor(floorNum/2));remainingEncounters=groups;for(let g=0;g<groups;g++){let cx=380+Math.random()*(WW-500),cy=100+Math.random()*(WH-200),amount=2+Math.floor(Math.random()*3)+Math.floor(floorNum/5);for(let i=0;i<amount;i++){const t=Math.random()<Math.min(.24+floorNum*.018,.5)?'archer':'melee',a=Math.random()*6.28,r=25+Math.random()*75,s=1+(floorNum-1)*.1,h=Math.round((t==='archer'?18:27)*s),ex=Math.max(55,Math.min(WW-55,cx+Math.cos(a)*r)),ey=Math.max(55,Math.min(WH-55,cy+Math.sin(a)*r));if(!validSpot(ex,ey,18)){ex=cx;ey=cy}enemies.push({id:id(),group:g,t,x:ex,y:ey,r:14,hp:h,max:h,dmg:Math.round((t==='archer'?6:13)*(1+floorNum*.065)),detect:t==='archer'?125:120,flash:0,active:false,aiming:false})}}U.res.textContent='Explore the expanded crypt. Search for loot and avoid detection circles.';updateCamera()}
function updateCamera(){cam.x=Math.max(0,Math.min(WW-VW,p.x-VW/2));cam.y=Math.max(0,Math.min(WH-VH,p.y-VH/2))}
function revealArea(){const gx=Math.floor(p.x/190),gy=Math.floor(p.y/118);discovered.add(`${gx},${gy}`)}
function collectLoot(){for(const l of loot){if(l.opened||Math.hypot(l.x-p.x,l.y-p.y)>p.r+l.r+9)continue;l.opened=true;if(l.type==='gold'){const amount=Math.round((8+Math.floor(Math.random()*15))*p.goldMult);gold+=amount;toast(`Gold +${amount}`);texts.push({x:l.x,y:l.y-18,t:`+${amount} GOLD`,l:1,crit:true})}else if(l.type==='health'){const heal=18+Math.floor(Math.random()*18),actual=Math.min(heal,p.max-p.hp);p.hp=Math.min(p.max,p.hp+heal);toast(actual?`Health +${actual}`:'Health already full');texts.push({x:l.x,y:l.y-18,t:actual?`+${actual} HP`:'FULL HP',l:1,crit:true})}else{const amount=Math.round((22+Math.floor(Math.random()*28))*p.goldMult),heal=10+Math.floor(Math.random()*16);gold+=amount;p.hp=Math.min(p.max,p.hp+heal);toast(`Chest: +${amount} gold, +${heal} HP`);texts.push({x:l.x,y:l.y-20,t:'TREASURE!',l:1.2,crit:true})}burst(l.x,l.y,14);ui()}loot=loot.filter(l=>!l.opened)}
function burst(px,py,n=8){for(let i=0;i<n;i++){let a=Math.random()*6.28,s=20+Math.random()*45;particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:.5})}}
function activeEnemies(){return enemies.filter(e=>encounterIds.has(e.id)&&e.hp>0)}
function target(){let list=activeEnemies(),e=list.find(e=>e.id===selected);return e||list.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]}
function startEncounter(trigger){if(mode!=='explore'||state!=='playing')return;mode='combat';turn='player';busy=true;encounterIds.clear();enemies.filter(e=>e.group===trigger.group||Math.hypot(e.x-trigger.x,e.y-trigger.y)<240).forEach(e=>{e.active=true;encounterIds.add(e.id)});selected=trigger.id;p.dodge=p.maxDodge;p.dodgeRecharge=0;U.res.innerHTML=`<strong>AMBUSH!</strong><br>${encounterIds.size} skeleton${encounterIds.size===1?'':'s'} entered combat.`;shake=9;ui();setTimeout(()=>{busy=false;ui()},450)}
function lineHitsCover(x1,y1,x2,y2){for(const o of cover){for(let i=0;i<=45;i++){const t=i/45,px=x1+(x2-x1)*t,py=y1+(y2-y1)*t;if(px>=o.x&&px<=o.x+o.w&&py>=o.y&&py<=o.y+o.h)return true}}return false}
function blockedPosition(nx,ny,r=p.r){return cover.some(o=>nx+r>o.x&&nx-r<o.x+o.w&&ny+r>o.y&&ny-r<o.y+o.h)}
async function roll(){if(state!=='playing'||mode!=='combat'||turn!=='player'||busy)return;let e=target();if(!e)return;let dist=Math.hypot(e.x-p.x,e.y-p.y);if(dist>p.range+e.r){U.res.innerHTML='<strong>Target is out of range.</strong><br>Move closer first.';return}busy=true;let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6),base=a+b+p.bonus,crit=Math.random()<p.crit,d=Math.round(base*(crit?p.critDmg:1));U.d1.classList.add('rolling');U.d2.classList.add('rolling');await wait(180);U.d1.classList.remove('rolling');U.d2.classList.remove('rolling');U.d1.textContent=a;U.d2.textContent=b;let interrupted=e.t==='archer'&&e.aiming;e.hp-=d;e.flash=.2;if(interrupted)e.aiming=false;U.res.innerHTML=crit?`<strong>CRITICAL!</strong><br>${a} + ${b} + ${p.bonus} = ${d} damage`:`${a} + ${b} + ${p.bonus} = <strong>${d} damage</strong>`;if(interrupted)U.res.innerHTML+='<br><strong>Archer interrupted!</strong>';texts.push({x:e.x,y:e.y-20,t:interrupted?'INTERRUPTED!':crit?`${d} CRIT!`:`${d}`,l:.9,crit:crit||interrupted});burst(e.x,e.y,crit?14:8);shake=crit?9:5;await wait(250);removeDead();advancePlayerTurnCounter();if(state==='playing'&&mode==='combat'&&activeEnemies().length)await enemyTurn();busy=false;ui()}
function advancePlayerTurnCounter(){if(p.dodge<p.maxDodge){p.dodgeRecharge++;if(p.dodgeRecharge>=3){p.dodge++;p.dodgeRecharge=0;texts.push({x:p.x,y:p.y-28,t:'DODGE +1',l:.9,crit:true})}}}
function combatMove(dx,dy,mult=1){if(state!=='playing'||mode!=='combat'||turn!=='player'||busy)return;busy=true;let len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;p.fx=dx;p.fy=dy;const step=p.step*mult,nx=Math.max(28,Math.min(WW-28,p.x+dx*step)),ny=Math.max(28,Math.min(WH-28,p.y+dy*step));if(!blockedPosition(nx,ny)){p.x=nx;p.y=ny}else texts.push({x:p.x,y:p.y-24,t:'BLOCKED',l:.6});updateCamera();advancePlayerTurnCounter();enemyTurn().then(()=>{busy=false;ui()})}
function dodge(){if(state!=='playing'||mode!=='combat'||turn!=='player'||busy||p.dodge<=0)return;busy=true;p.dodge--;p.dodging=true;let dx=p.fx,dy=p.fy;if(!dx&&!dy)dx=1;const nx=Math.max(28,Math.min(WW-28,p.x+dx*p.step*2)),ny=Math.max(28,Math.min(WH-28,p.y+dy*p.step*2));if(!blockedPosition(nx,ny)){p.x=nx;p.y=ny}updateCamera();texts.push({x:p.x,y:p.y-28,t:'DODGE!',l:.8,crit:true});U.res.innerHTML='<strong>Dodge!</strong><br>You evade the entire enemy phase.';advancePlayerTurnCounter();enemyTurn().then(()=>{p.dodging=false;busy=false;ui()})}
function hurt(n,sx,sy){if(p.dodging){texts.push({x:p.x,y:p.y-24,t:'DODGED!',l:.9,crit:true});return}n=Math.max(1,n-p.armor);p.hp-=n;shake=9;texts.push({x:p.x,y:p.y-24,t:`-${n}`,l:.9,player:true});if(p.hp<=0)end()}
function enemyDice(e){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6),crit=a===6&&b===6;return {a,b,crit,dmg:Math.max(1,Math.round((a+b)*(e.dmg/10)*(crit?1.6:1)))}}
async function enemyTurn(){if(state!=='playing'||mode!=='combat')return;turn='enemy';ui();await wait(220);for(const e of activeEnemies()){if(state!=='playing'||e.hp<=0)continue;let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(e.t==='melee'){if(d<=52){const r=enemyDice(e);texts.push({x:e.x,y:e.y-20,t:`${r.a}+${r.b}`,l:.55});hurt(r.dmg,e.x,e.y)}else{let step=Math.min(48,d-42),nx=e.x+dx/d*step,ny=e.y+dy/d*step;if(!blockedPosition(nx,ny,e.r)){e.x=nx;e.y=ny}}}else{if(e.aiming){if(lineHitsCover(e.x,e.y,p.x,p.y)){e.aiming=false;texts.push({x:e.x,y:e.y-20,t:'SHOT BLOCKED',l:.7,crit:true})}else{const r=enemyDice(e);texts.push({x:e.x,y:e.y-20,t:r.crit?'DEADLY SHOT!':`${r.a}+${r.b}`,l:.65,crit:r.crit});await wait(140);hurt(r.dmg,e.x,e.y);e.aiming=false}}else if(d<=420&&d>=115&&!lineHitsCover(e.x,e.y,p.x,p.y)){e.aiming=true;texts.push({x:e.x,y:e.y-20,t:'AIMING...',l:.9,crit:true})}else{let dir=d<115?-1:1,step=38,nx=Math.max(28,Math.min(WW-28,e.x+dx/d*step*dir)),ny=Math.max(28,Math.min(WH-28,e.y+dy/d*step*dir));if(!blockedPosition(nx,ny,e.r)){e.x=nx;e.y=ny}}}ui();await wait(260)}if(state==='playing'&&mode==='combat'){turn='player';U.res.innerHTML=p.dodging?'You dodged the enemy phase.':'Your turn. Attack, move, interrupt an archer, or dodge.';ui()}}
function removeDead(){enemies=enemies.filter(e=>{if(e.hp<=0){kills++;const reward=Math.round((e.t==='archer'?7:5)*p.goldMult);gold+=reward;burst(e.x,e.y,14);encounterIds.delete(e.id);if(selected===e.id)selected=null;return false}return true});if(mode==='combat'&&!activeEnemies().length&&state==='playing')setTimeout(endEncounter,350)}
function endEncounter(){mode='explore';turn='none';busy=false;selected=null;encounterIds.clear();remainingEncounters=Math.max(0,remainingEncounters-1);p.hp=Math.min(p.max,p.hp+6);p.dodging=false;if(!enemies.length||remainingEncounters===0)setTimeout(floorComplete,350);else{U.res.innerHTML='<strong>Encounter cleared.</strong><br>Exploration resumed. Search for loot or find the next patrol.';ui()}}
function floorComplete(){if(state!=='playing')return;if(floorNum%5===0)openShop();else choose()}
function openShop(){state='shop';turn='none';U.shop.classList.add('visible');renderShop()}
function renderShop(){U.shopGold.textContent=`Gold: ${gold}`;U.shopOptions.innerHTML='';[...shopStock].sort(()=>Math.random()-.5).slice(0,4).forEach(v=>{let b=document.createElement('button');b.className='upgrade-option';b.disabled=gold<v[1];b.innerHTML=`<strong>${v[0]} — ${v[1]}g</strong><span>${v[2]}</span>`;b.onclick=()=>{if(gold<v[1])return;gold-=v[1];v[3]();toast(`Purchased ${v[0]}`);renderShop();ui()};U.shopOptions.appendChild(b)})}
function leaveShop(){U.shop.classList.remove('visible');floorNum++;state='playing';spawnFloor();ui()}
function end(){state='over';turn='none';U.stats.textContent=`You reached floor ${floorNum}, defeated ${kills} skeletons, and collected ${gold} gold.`;U.over.classList.add('visible')}
function choose(){if(state!=='playing')return;state='upgrade';turn='none';U.up.classList.add('visible');U.ups.innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(v=>{let b=document.createElement('button');b.className='upgrade-option';b.innerHTML=`<strong>${v[0]}</strong><span>${v[1]}</span>`;b.onclick=()=>{v[2]();floorNum++;p.hp=Math.min(p.max,p.hp+10);U.up.classList.remove('visible');state='playing';spawnFloor();ui()};U.ups.appendChild(b)})}
function update(dt){if(state==='playing'&&mode==='explore'&&!busy){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(dx,dy);if(l){dx/=l;dy/=l;p.fx=dx;p.fy=dy;let nx=Math.max(28,Math.min(WW-28,p.x+dx*p.exploreSpeed*dt)),ny=Math.max(28,Math.min(WH-28,p.y+dy*p.exploreSpeed*dt));if(!blockedPosition(nx,ny)){p.x=nx;p.y=ny}}updateCamera();revealArea();collectLoot();const trigger=enemies.find(e=>!e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=e.detect+p.r);if(trigger)startEncounter(trigger)}particles.forEach(o=>{o.x+=o.vx*dt;o.y+=o.vy*dt;o.vx*=.94;o.vy*=.94;o.l-=dt});particles=particles.filter(o=>o.l>0);texts.forEach(t=>{t.y-=22*dt;t.l-=dt});texts=texts.filter(t=>t.l>0);enemies.forEach(e=>e.flash=Math.max(0,e.flash-dt))}
function worldFloor(){x.fillStyle='#120e18';x.fillRect(0,0,VW,VH);x.save();x.translate(-cam.x,-cam.y);x.strokeStyle='#21182a';x.lineWidth=1;for(let i=0;i<WW;i+=48){x.beginPath();x.moveTo(i,0);x.lineTo(i,WH);x.stroke()}for(let i=0;i<WH;i+=48){x.beginPath();x.moveTo(0,i);x.lineTo(WW,i);x.stroke()}x.strokeStyle='#4b3858';x.lineWidth=7;x.strokeRect(12,12,WW-24,WH-24);cover.forEach(o=>{x.fillStyle=o.type==='wall'?'#4a4050':o.type==='crate'?'#6e4b2c':'#57505f';x.fillRect(o.x,o.y,o.w,o.h);x.strokeStyle='#85798c';x.lineWidth=3;x.strokeRect(o.x,o.y,o.w,o.h)});loot.forEach(l=>{if(l.type==='gold'){x.fillStyle='#e4b14d';x.beginPath();x.arc(l.x,l.y,9,0,6.28);x.fill();x.fillStyle='#fff1a5';x.fillRect(l.x-2,l.y-6,4,12)}else if(l.type==='health'){x.fillStyle='#b83345';x.fillRect(l.x-9,l.y-11,18,22);x.fillStyle='#f8e8e8';x.fillRect(l.x-3,l.y-8,6,16);x.fillRect(l.x-7,l.y-4,14,7)}else{x.fillStyle='#7c4e25';x.fillRect(l.x-17,l.y-13,34,27);x.strokeStyle='#d3a650';x.lineWidth=3;x.strokeRect(l.x-17,l.y-13,34,27);x.fillStyle='#f0c879';x.fillRect(l.x-3,l.y-2,6,8)}})}
function sk(e){x.save();x.translate(e.x,e.y);if(mode==='explore'&&!e.active){x.strokeStyle=e.t==='archer'?'#c95f5f55':'#ef7b6755';x.fillStyle='#c95f5f0d';x.lineWidth=2;x.beginPath();x.arc(0,0,e.detect,0,6.28);x.fill();x.stroke()}if(e.aiming&&mode==='combat'){x.strokeStyle='#ff4747';x.lineWidth=3;x.setLineDash([9,7]);x.beginPath();x.moveTo(0,0);x.lineTo(p.x-e.x,p.y-e.y);x.stroke();x.setLineDash([])}if(e.flash)x.globalAlpha=.45;if(e.id===selected){x.strokeStyle='#f0c879';x.lineWidth=3;x.beginPath();x.arc(0,3,24,0,6.28);x.stroke()}x.fillStyle=e.t==='archer'?'#c9bb9d':'#e1d5b8';x.beginPath();x.arc(0,-7,10,0,6.28);x.fill();x.strokeStyle='#d8cbae';x.lineWidth=4;x.beginPath();x.moveTo(0,3);x.lineTo(0,17);x.moveTo(-9,8);x.lineTo(9,8);x.moveTo(0,17);x.lineTo(-8,27);x.moveTo(0,17);x.lineTo(8,27);x.stroke();x.fillStyle='#1b1720';x.fillRect(-5,-10,3,3);x.fillRect(2,-10,3,3);if(e.t==='archer'){x.strokeStyle=e.aiming?'#ff4747':'#9b6c3f';x.lineWidth=2;x.beginPath();x.arc(12,7,9,-1.57,1.57);x.stroke()}else{x.strokeStyle='#aeb4bf';x.lineWidth=4;x.beginPath();x.moveTo(10,2);x.lineTo(18,-10);x.stroke()}x.restore();if(mode==='combat'&&encounterIds.has(e.id)){x.fillStyle='#2a1015';x.fillRect(e.x-17,e.y-28,34,5);x.fillStyle='#c74c58';x.fillRect(e.x-17,e.y-28,34*Math.max(0,e.hp)/e.max,5)}}
function player(){x.save();x.translate(p.x,p.y);if(p.dodging)x.globalAlpha=.45;x.fillStyle='#57427c';x.beginPath();x.arc(0,0,16,0,6.28);x.fill();x.fillStyle='#d5b48a';x.beginPath();x.arc(0,-7,9,0,6.28);x.fill();x.strokeStyle='#f0c879';x.lineWidth=4;x.beginPath();x.moveTo(4,2);x.lineTo(p.fx*20,p.fy*20);x.stroke();x.restore();if(mode==='combat'&&turn==='player'){x.strokeStyle='#f0c87955';x.lineWidth=2;x.beginPath();x.arc(p.x,p.y,p.range,0,6.28);x.stroke()}}
function minimap(){const w=150,h=90,ox=VW-w-14,oy=14;x.fillStyle='#08070bcc';x.fillRect(ox,oy,w,h);x.strokeStyle='#695378';x.strokeRect(ox,oy,w,h);const sx=w/WW,sy=h/WH;cover.forEach(o=>{x.fillStyle='#4e4655';x.fillRect(ox+o.x*sx,oy+o.y*sy,Math.max(2,o.w*sx),Math.max(2,o.h*sy))});loot.forEach(l=>{x.fillStyle=l.type==='health'?'#cf4f5b':'#d8a657';x.fillRect(ox+l.x*sx-1,oy+l.y*sy-1,3,3)});enemies.forEach(e=>{x.fillStyle='#a94c54';x.fillRect(ox+e.x*sx-1,oy+e.y*sy-1,3,3)});x.fillStyle='#f5f1ff';x.beginPath();x.arc(ox+p.x*sx,oy+p.y*sy,3,0,6.28);x.fill()}
function draw(){let sx=shake?(Math.random()-.5)*shake:0,sy=shake?(Math.random()-.5)*shake:0;shake*=.82;x.save();x.translate(sx,sy);worldFloor();particles.forEach(o=>{x.globalAlpha=Math.max(0,o.l*2);x.fillStyle='#e8c77e';x.fillRect(o.x-2,o.y-2,4,4);x.globalAlpha=1});enemies.forEach(sk);player();texts.forEach(t=>{x.globalAlpha=Math.max(0,t.l);x.fillStyle=t.player?'#ff6d72':t.crit?'#ffd56d':'#fff';x.font=t.crit?'bold 20px sans-serif':'bold 16px sans-serif';x.textAlign='center';x.fillText(t.t,t.x,t.y);x.globalAlpha=1});x.restore();minimap();x.restore()}
function ui(){U.hp.style.width=`${Math.max(0,p.hp/p.max*100)}%`;U.hpt.textContent=`${Math.max(0,Math.ceil(p.hp))} / ${p.max}`;U.room.textContent=floorNum;U.gold.textContent=gold;U.crit.textContent=`${Math.round(p.crit*100)}%`;U.cd.textContent=`${p.critDmg.toFixed(1)}×`;U.db.textContent=`+${p.bonus}`;U.spd.textContent=p.step;U.rng.textContent=Math.round(p.range);U.dash.textContent=`${p.dodge} / ${p.maxDodge}`;U.explored.textContent=`${Math.min(100,Math.round(discovered.size/100*100))}%`;U.turn.innerHTML=mode==='explore'?'<strong>Exploration</strong>':turn==='player'?'<strong>Your Turn</strong>':'<strong>Enemy Turn</strong>';U.roll.disabled=busy||mode!=='combat'||turn!=='player'||state!=='playing';U.dodge.disabled=busy||mode!=='combat'||turn!=='player'||state!=='playing'||p.dodge<=0;U.dodge.textContent=`Dodge — ${p.dodge}/${p.maxDodge}`}
let last=0;function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
document.addEventListener('keydown',e=>{let k=e.key.toLowerCase();keys[k]=true;if(e.code==='Space'){e.preventDefault();roll();return}if(k==='shift'){e.preventDefault();dodge();return}if(e.repeat||mode!=='combat')return;if(k==='w'||k==='arrowup')combatMove(0,-1);if(k==='s'||k==='arrowdown')combatMove(0,1);if(k==='a'||k==='arrowleft')combatMove(-1,0);if(k==='d'||k==='arrowright')combatMove(1,0)});document.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
c.addEventListener('click',e=>{if(state!=='playing'||mode!=='combat'||turn!=='player'||busy)return;let r=c.getBoundingClientRect(),mx=(e.clientX-r.left)*VW/r.width+cam.x,my=(e.clientY-r.top)*VH/r.height+cam.y,hit=activeEnemies().slice().reverse().find(v=>Math.hypot(v.x-mx,v.y-my)<28);if(hit){selected=hit.id;U.res.innerHTML=`Targeted <strong>${hit.t==='archer'?'Archer':'Melee'} Skeleton</strong>. Press Space to roll.`;ui()}});
U.roll.onclick=roll;U.dodge.onclick=dodge;U.leaveShop.onclick=leaveShop;q('start-btn').onclick=()=>{reset();state='playing';U.start.classList.remove('visible');ui()};q('restart-btn').onclick=()=>{U.over.classList.remove('visible');reset();state='playing';ui()};draw();requestAnimationFrame(loop);
