'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const statsEl=document.getElementById('stats'),hotbarEl=document.getElementById('hotbar'),loading=document.getElementById('loading'),craftPanel=document.getElementById('crafting'),recipesEl=document.getElementById('recipes'),msgEl=document.getElementById('message');
let W=innerWidth,H=innerHeight,DPR=Math.min(devicePixelRatio||1,2);function resize(){W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
const TILE=24, WORLD_W=320, WORLD_H=120;
const AIR=0,GRASS=1,DIRT=2,STONE=3,WOOD=4,LEAF=5,COAL=6,IRON=7,SAND=8,PLANK=9,TORCH=10;
const defs={0:{name:'Air',solid:false},1:{name:'Grass',solid:true,hp:18},2:{name:'Dirt',solid:true,hp:14},3:{name:'Stone',solid:true,hp:34},4:{name:'Wood',solid:true,hp:24},5:{name:'Leaf',solid:false,hp:8},6:{name:'Coal',solid:true,hp:38},7:{name:'Iron',solid:true,hp:48},8:{name:'Sand',solid:true,hp:12},9:{name:'Plank',solid:true,hp:18},10:{name:'Torch',solid:false,hp:5}};
const colors={1:'#4ebc52',2:'#7b4d2d',3:'#66707c',4:'#8c5429',5:'#3b9e43',6:'#30343a',7:'#a66b56',8:'#d8be72',9:'#bd793d',10:'#ffb52d'};
let world=[],damage=new Map(),surface=[],particles=[],enemies=[],drops=[],stars=[],time=0.18,day=1,camera={x:0,y:0},shake=0;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function noise1(x){return Math.sin(x*.15)*3+Math.sin(x*.047)*7+Math.sin(x*.31)*1.4}
function generate(){world=Array.from({length:WORLD_H},()=>new Uint8Array(WORLD_W));for(let x=0;x<WORLD_W;x++){let s=Math.floor(39+noise1(x));surface[x]=s;for(let y=s;y<WORLD_H;y++){let t=y===s?GRASS:y<s+7?DIRT:STONE;if(x>235&&x<270&&y<s+8)t=y===s?SAND:SAND;world[y][x]=t}}
 for(let i=0;i<150;i++){let cx=rand(4,WORLD_W-4),cy=rand(47,WORLD_H-8),r=rand(2,7);for(let y=Math.floor(cy-r);y<cy+r;y++)for(let x=Math.floor(cx-r*1.6);x<cx+r*1.6;x++)if((x-cx)**2/(r*r*2.5)+(y-cy)**2/(r*r)<1&&y>surface[x]+3)world[y][x]=AIR}
 for(let i=0;i<240;i++){let x=Math.floor(rand(3,WORLD_W-3)),y=Math.floor(rand(50,WORLD_H-5)),ore=Math.random()<.27?IRON:COAL;for(let j=0;j<rand(2,7);j++){let ox=clamp(x+Math.floor(rand(-2,3)),1,WORLD_W-2),oy=clamp(y+Math.floor(rand(-2,3)),1,WORLD_H-2);if(world[oy][ox]===STONE)world[oy][ox]=ore}}
 for(let x=8;x<WORLD_W-8;x+=Math.floor(rand(8,15))){if(x>232&&x<275)continue;let s=surface[x];if(world[s][x]===GRASS){let h=Math.floor(rand(4,8));for(let y=s-1;y>s-h;y--)world[y][x]=WOOD;for(let yy=s-h-2;yy<=s-h+2;yy++)for(let xx=x-3;xx<=x+3;xx++)if((xx-x)**2+(yy-(s-h))**2<10&&world[yy]?.[xx]===AIR)world[yy][xx]=LEAF}}
 stars=Array.from({length:150},()=>({x:Math.random()*W,y:Math.random()*H*.65,s:rand(1,2.6)}));}
const inventory={Dirt:30,Stone:0,Wood:0,Coal:0,Iron:0,Plank:0,Torch:4,Sword:1,Pickaxe:1};
const slots=['Pickaxe','Sword','Dirt','Stone','Wood','Plank','Torch','Sand'];let selected=0;
const player={x:30*TILE,y:20*TILE,w:18,h:38,vx:0,vy:0,onGround:false,facing:1,hp:100,maxHp:100,armor:0,attackCd:0,mining:0};
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(/^Digit[1-8]$/.test(e.code))selected=+e.code.slice(5)-1;if(e.code==='KeyC'){craftPanel.classList.toggle('hidden');renderRecipes()}if(e.code==='KeyR')location.reload()});addEventListener('keyup',e=>keys[e.code]=false);
const mouse={x:0,y:0,left:false,right:false};canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('mousedown',e=>{if(e.button===0)mouse.left=true;if(e.button===2){mouse.right=true;placeBlock()}});addEventListener('mouseup',e=>{if(e.button===0)mouse.left=false;if(e.button===2)mouse.right=false});canvas.oncontextmenu=e=>e.preventDefault();
function tileAt(px,py){let x=Math.floor(px/TILE),y=Math.floor(py/TILE);return world[y]?.[x]??STONE}function solidAt(px,py){return !!defs[tileAt(px,py)]?.solid}
function moveEntity(o,dt){o.x+=o.vx*dt;let left=o.x-o.w/2,right=o.x+o.w/2,top=o.y-o.h/2,bottom=o.y+o.h/2;if(o.vx>0&&(solidAt(right,top+3)||solidAt(right,bottom-2))){o.x=Math.floor(right/TILE)*TILE-o.w/2-.01;o.vx=0}if(o.vx<0&&(solidAt(left,top+3)||solidAt(left,bottom-2))){o.x=(Math.floor(left/TILE)+1)*TILE+o.w/2+.01;o.vx=0}
 o.y+=o.vy*dt;left=o.x-o.w/2;right=o.x+o.w/2;top=o.y-o.h/2;bottom=o.y+o.h/2;o.onGround=false;if(o.vy>0&&(solidAt(left+2,bottom)||solidAt(right-2,bottom))){o.y=Math.floor(bottom/TILE)*TILE-o.h/2-.01;o.vy=0;o.onGround=true}if(o.vy<0&&(solidAt(left+2,top)||solidAt(right-2,top))){o.y=(Math.floor(top/TILE)+1)*TILE+o.h/2+.01;o.vy=0}}
function cursorTile(){return{x:Math.floor((mouse.x+camera.x)/TILE),y:Math.floor((mouse.y+camera.y)/TILE)}}
function distanceToTile(t){return Math.hypot((t.x+.5)*TILE-player.x,(t.y+.5)*TILE-player.y)}
function mine(){if(!mouse.left)return;let item=slots[selected];if(item==='Sword'){attack();return}if(item!=='Pickaxe')return;let t=cursorTile();if(distanceToTile(t)>TILE*5||!world[t.y]?.[t.x])return;let key=t.x+','+t.y,type=world[t.y][t.x],power=type===IRON?24:35,amt=(damage.get(key)||0)+power/60;damage.set(key,amt);player.mining=.1;if(amt>=defs[type].hp){world[t.y][t.x]=AIR;damage.delete(key);let name=defs[type].name;if(name==='Grass')name='Dirt';inventory[name]=(inventory[name]||0)+1;burst((t.x+.5)*TILE,(t.y+.5)*TILE,colors[type],8);show('+1 '+name);renderHotbar()}}
function placeBlock(){let name=slots[selected],map={Dirt:DIRT,Stone:STONE,Wood:WOOD,Plank:PLANK,Torch:TORCH,Sand:SAND};let id=map[name];if(!id||!inventory[name])return;let t=cursorTile();if(distanceToTile(t)>TILE*5||world[t.y]?.[t.x]!==AIR)return;let bx=t.x*TILE,by=t.y*TILE;if(player.x+player.w/2>bx&&player.x-player.w/2<bx+TILE&&player.y+player.h/2>by&&player.y-player.h/2<by+TILE)return;world[t.y][t.x]=id;inventory[name]--;renderHotbar()}
function attack(){if(player.attackCd>0)return;player.attackCd=.35;let range=58;for(const e of enemies){if(Math.hypot(e.x-player.x,e.y-player.y)<range){e.hp-=28;e.vx=player.facing*180;e.vy=-130;burst(e.x,e.y,'#8bd45c',7);shake=5}}}
function burst(x,y,c,n){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-110,110),vy:rand(-160,20),life:rand(.25,.7),c,s:rand(2,5)})}
function show(s){msgEl.textContent=s;msgEl.style.opacity=1;clearTimeout(show.t);show.t=setTimeout(()=>msgEl.style.opacity=0,800)}
function spawnEnemy(){let night=time>.72||time<.18;if(!night||enemies.length>10)return;let x=player.x+rand(450,850)*(Math.random()<.5?-1:1);x=clamp(x,3*TILE,(WORLD_W-3)*TILE);let tx=Math.floor(x/TILE),y=(surface[tx]-2)*TILE;enemies.push({x,y,w:30,h:24,vx:0,vy:0,hp:55,onGround:false,jump:rand(.5,2),hurt:0})}
function updateEnemy(e,dt){let d=player.x-e.x;e.vx+=Math.sign(d)*170*dt;e.vx=clamp(e.vx,-65,65);e.vy+=620*dt;e.jump-=dt;if(e.onGround&&e.jump<0){e.vy=-rand(190,280);e.jump=rand(.8,2)}moveEntity(e,dt);e.hurt-=dt;if(Math.hypot(e.x-player.x,e.y-player.y)<30&&e.hurt<=0){player.hp-=8;e.hurt=1;player.vx=Math.sign(player.x-e.x)*180;player.vy=-120;shake=8;show('-8 HP')}}
const recipes=[{name:'4 Planks',cost:{Wood:1},give:{Plank:4}},{name:'4 Torches',cost:{Wood:1,Coal:1},give:{Torch:4}},{name:'Iron Armor (+10 armor)',cost:{Iron:12},special:()=>player.armor+=10},{name:'Healing (+30 HP)',cost:{Wood:3,Coal:2},special:()=>player.hp=Math.min(player.maxHp,player.hp+30)}];
function canCraft(r){return Object.entries(r.cost).every(([k,v])=>(inventory[k]||0)>=v)}function craft(i){let r=recipes[i];if(!canCraft(r))return;for(const[k,v]of Object.entries(r.cost))inventory[k]-=v;if(r.give)for(const[k,v]of Object.entries(r.give))inventory[k]=(inventory[k]||0)+v;if(r.special)r.special();renderRecipes();renderHotbar();show('Crafted '+r.name)}
function renderRecipes(){recipesEl.innerHTML=recipes.map((r,i)=>`<div class="recipe"><span><b>${r.name}</b><br>${Object.entries(r.cost).map(([k,v])=>v+' '+k).join(' + ')}</span><button ${canCraft(r)?'':'disabled'} onclick="craft(${i})">Craft</button></div>`).join('')}
window.craft=craft;
function renderHotbar(){hotbarEl.innerHTML=slots.map((s,i)=>`<div class="slot ${i===selected?'selected':''}"><b>${i+1}</b>${s}<span class="count">${['Pickaxe','Sword'].includes(s)?'∞':inventory[s]||0}</span></div>`).join('')}
function update(dt){time+=dt*.008;if(time>=1){time-=1;day++}let move=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0);player.vx+=move*900*dt;player.vx*=Math.pow(.0008,dt);player.vx=clamp(player.vx,-190,190);if(move)player.facing=move;if((keys.Space||keys.KeyW||keys.ArrowUp)&&player.onGround)player.vy=-360;player.vy+=900*dt;moveEntity(player,dt);player.attackCd-=dt;player.mining-=dt;mine();
 if(Math.random()<dt*.28)spawnEnemy();for(const e of enemies)updateEnemy(e,dt);enemies=enemies.filter(e=>{if(e.hp<=0){burst(e.x,e.y,'#62c95f',14);inventory.Coal=(inventory.Coal||0)+(Math.random()<.5?1:0);return false}return e.y<WORLD_H*TILE+100});
 for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=420*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);if(player.hp<=0){player.hp=100;player.x=30*TILE;player.y=20*TILE;show('You respawned')}
 let targetX=player.x-W*.5,targetY=player.y-H*.55;camera.x+=(targetX-camera.x)*Math.min(1,dt*5);camera.y+=(targetY-camera.y)*Math.min(1,dt*5);camera.x=clamp(camera.x,0,WORLD_W*TILE-W);camera.y=clamp(camera.y,0,WORLD_H*TILE-H);shake*=Math.pow(.02,dt);renderHotbar();}
function sky(){let sun=Math.max(0,Math.sin(time*Math.PI*2-Math.PI/2)*.5+.5),r=Math.floor(9+72*sun),g=Math.floor(17+150*sun),b=Math.floor(35+195*sun);ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(0,0,W,H);let night=1-sun;ctx.globalAlpha=night;ctx.fillStyle='#fff';for(const s of stars){ctx.fillRect(s.x,s.y,s.s,s.s)}ctx.globalAlpha=1;let ang=time*Math.PI*2-Math.PI;let sx=W/2+Math.cos(ang)*W*.52,sy=H*.8+Math.sin(ang)*H*.62;ctx.fillStyle=sun>.3?'#ffe374':'#d9e8ff';ctx.beginPath();ctx.arc(sx,sy,30,0,Math.PI*2);ctx.fill();ctx.fillStyle=`rgba(35,60,85,${.22+.25*night})`;for(let i=0;i<12;i++){let x=(i*180-camera.x*.12)% (W+250)-100,y=H*.58+Math.sin(i*1.9)*45;ctx.beginPath();ctx.moveTo(x-140,H);ctx.lineTo(x,y);ctx.lineTo(x+150,H);ctx.fill()}}
function drawTile(id,x,y){let sx=x*TILE-camera.x,sy=y*TILE-camera.y;if(id===AIR)return;ctx.fillStyle=colors[id];ctx.fillRect(sx,sy,TILE,TILE);if(id===GRASS){ctx.fillStyle='#8bd34c';ctx.fillRect(sx,sy,TILE,5)}else if(id===DIRT||id===STONE||id===COAL||id===IRON||id===SAND){ctx.fillStyle='#ffffff18';ctx.fillRect(sx+3+(x*7+y*3)%12,sy+4+(x*11)%13,3,3);ctx.fillStyle='#00000024';ctx.fillRect(sx+13+(x*5)%7,sy+14+(y*5)%6,4,3)}else if(id===WOOD||id===PLANK){ctx.fillStyle='#0002';ctx.fillRect(sx+5,sy,3,TILE);ctx.fillRect(sx+16,sy,2,TILE)}else if(id===LEAF){ctx.globalAlpha=.82;ctx.fillStyle=colors[id];ctx.beginPath();ctx.arc(sx+12,sy+12,13,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}else if(id===TORCH){ctx.fillStyle='#7c4b1f';ctx.fillRect(sx+10,sy+8,4,15);ctx.fillStyle='#fff18b';ctx.beginPath();ctx.arc(sx+12,sy+7,6,0,Math.PI*2);ctx.fill()}ctx.strokeStyle='#00000018';ctx.strokeRect(sx,sy,TILE,TILE)}
function drawPlayer(){let x=player.x-camera.x,y=player.y-camera.y;ctx.save();ctx.translate(x,y);ctx.scale(player.facing,1);ctx.fillStyle='#273451';ctx.fillRect(-8,-1,16,19);ctx.fillStyle='#d69a6a';ctx.fillRect(-7,-18,14,16);ctx.fillStyle='#3a2617';ctx.fillRect(-8,-20,16,6);ctx.fillStyle='#16223a';ctx.fillRect(-8,18,7,4);ctx.fillRect(2,18,7,4);ctx.fillStyle='#eaf4ff';ctx.fillRect(2,-13,3,3);if(player.attackCd>.15){ctx.strokeStyle='#dce9ef';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(8,-2);ctx.lineTo(37,-24);ctx.stroke()}else if(player.mining>0){ctx.strokeStyle='#a8b1bd';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(28,-18);ctx.stroke()}ctx.restore()}
function draw(){ctx.save();let ox=rand(-shake,shake),oy=rand(-shake,shake);ctx.translate(ox,oy);sky();let x0=Math.max(0,Math.floor(camera.x/TILE)-1),x1=Math.min(WORLD_W,Math.ceil((camera.x+W)/TILE)+1),y0=Math.max(0,Math.floor(camera.y/TILE)-1),y1=Math.min(WORLD_H,Math.ceil((camera.y+H)/TILE)+1);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++)drawTile(world[y][x],x,y);
 for(const [key,d] of damage){let[x,y]=key.split(',').map(Number),sx=x*TILE-camera.x,sy=y*TILE-camera.y;ctx.strokeStyle='#fff8';ctx.lineWidth=2;let n=Math.min(5,Math.floor(d/7));for(let i=0;i<n;i++){ctx.beginPath();ctx.moveTo(sx+4+i*3,sy+4);ctx.lineTo(sx+10+i*2,sy+20);ctx.stroke()}}
 for(const e of enemies){let x=e.x-camera.x,y=e.y-camera.y;ctx.fillStyle='#59b94d';ctx.beginPath();ctx.ellipse(x,y,16,12,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#15351a';ctx.fillRect(x-7,y-3,3,3);ctx.fillRect(x+5,y-3,3,3)}drawPlayer();for(const p of particles){ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.c;ctx.fillRect(p.x-camera.x,p.y-camera.y,p.s,p.s)}ctx.globalAlpha=1;let t=cursorTile();if(distanceToTile(t)<TILE*5){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(t.x*TILE-camera.x,t.y*TILE-camera.y,TILE,TILE)}ctx.restore();let night=time>.72||time<.18;statsEl.innerHTML=`❤️ HP ${Math.ceil(player.hp)}/${player.maxHp}<br>🛡️ Armor ${player.armor}<br>${night?'🌙 Night':'☀️ Day'} ${day}`;}
let last=performance.now();function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}generate();player.y=(surface[30]-3)*TILE;renderHotbar();renderRecipes();loading.style.display='none';requestAnimationFrame(loop);
